feat: print a more user-friendly error when pinning plugin-ci-workflows to a commit hash

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -235,6 +235,14 @@ on:
         type: string
         required: false
         default: ""
+      allow-pinned-commit-hashes:
+        description: |
+          If `true`, skip hard fail in case the workflow is pinned to a commit hash.
+          Vault access may still fail in such cases, depending on the WIF policies in place.
+          This should only be used for testing repositories and should not be changed in most cases.
+        type: boolean
+        required: false
+        default: false
 
     outputs:
       plugin:
@@ -305,7 +313,7 @@ jobs:
             echo "Found usage of rolling releases channel in the following files:"
             echo "$diff"
 
-            title="Rolling release channel detected"
+            title="Detected plugin-ci-workflows rolling release channel"
             message="You are using workflows from plugin-ci-workflows rolling releases channel (\`@main\`). \
           This is discouraged as it may lead to unexpected breaking changes. \
           Please pin to a specific tagged release to ensure better stability. \
@@ -314,6 +322,31 @@ jobs:
             echo "::warning title=$title::$message"
             exit 0
           fi
+        shell: bash
+
+      - name: Check for plugin-ci-workflows pinned to commit hash
+        run: |
+          diff=$(grep -E 'grafana/plugin-ci-workflows.+@[0-9a-f]{6,40}' -rn .github/workflows/ || true)
+          if [[ -n "$diff" ]]; then
+            echo "Found plugin-ci-workflows pinned to a commit hash in the following files:"
+            echo "$diff"
+
+            title="Detected plugin-ci-workflows pinned to a commit hash"
+            message="You are pinning plugin-ci-workflows to a commit hash. \
+          To limit the amount of exposure (security reasons), this is not allowed and the workflow will fail. \
+          Please pin to a specific tagged release instead. \
+          For more information, refer to the docs: https://enghub.grafana-ops.net/docs/default/component/grafana-plugins-platform/plugins-ci-github-actions/010-plugins-ci-github-actions/#versions-and-release-channels"
+
+            echo "::warning title=$title::$message"
+            if [ "${ALLOW_PINNED_COMMIT_HASHES}" != "true" ]; then
+              # Hard fail by default
+              exit 1
+            else
+              exit 0
+            fi
+          fi
+        env:
+          ALLOW_PINNED_COMMIT_HASHES: ${{ inputs.allow-pinned-commit-hashes }}
         shell: bash
 
   test-and-build:
